services:
  backend:
    build: ./backend
    container_name: finance_backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
      - JwtConfig__Key=${JWT_KEY}
    ports:
      - "8080:8080"
      
  frontend:
    build: ./frontend
    container_name: finance_frontend
    depends_on:
      - backend
    ports:
      - "3000:80"